"""
保留真实有效分支及版本准备的三侧内容和原子结果。
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0034_skill_branch_preparation"
down_revision = "0033_skill_state_operations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    增加精确同源约束和独立准备记录，不推断旧数据的实际使用顺序。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "skill_state_installation_identity_uq",
        "account_skill_states",
        ["user_id", "account_id", "installation_id", "installation_epoch", "id"],
    )
    op.create_table(
        "skill_effective_branches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.Uuid(), nullable=False),
        sa.Column("installation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "state_id"],
            ["session_skill_snapshot_items.snapshot_id", "session_skill_snapshot_items.state_id"],
            name="skill_effective_member_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "account_id", "installation_id", "installation_epoch", "state_id"],
            [
                "account_skill_states.user_id",
                "account_skill_states.account_id",
                "account_skill_states.installation_id",
                "account_skill_states.installation_epoch",
                "account_skill_states.id",
            ],
            name="skill_effective_branch_fk",
        ),
        sa.PrimaryKeyConstraint("account_id", "installation_id", "installation_epoch"),
    )
    op.create_table(
        "skill_branch_preparations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.Uuid(), nullable=False),
        sa.Column("installation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("target_state_id", sa.Uuid(), nullable=False),
        sa.Column("target_epoch", sa.BigInteger(), nullable=False),
        sa.Column("source_state_id", sa.Uuid(), nullable=True),
        sa.Column("source_epoch", sa.BigInteger(), nullable=True),
        sa.Column("source_checkpoint_id", sa.Uuid(), nullable=True),
        sa.Column("directory_epoch", sa.BigInteger(), nullable=False),
        sa.Column("library_generation", sa.BigInteger(), nullable=False),
        sa.Column("directory_scope", sa.String(length=16), nullable=False),
        sa.Column("directory_checkpoint_id", sa.Uuid(), nullable=False),
        sa.Column("result_checkpoint_id", sa.Uuid(), nullable=True),
        sa.Column("result_directory_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("base_digest", sa.String(length=64), nullable=False),
        sa.Column("current_digest", sa.String(length=64), nullable=False),
        sa.Column("incoming_digest", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "response_json",
            postgresql.JSONB(),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'ready' AND result_checkpoint_id IS NOT NULL AND "
            "result_directory_id IS NOT NULL) OR (status <> 'ready' AND "
            "result_checkpoint_id IS NULL AND result_directory_id IS NULL)",
            name="skill_preparation_result_ck",
        ),
        sa.CheckConstraint(
            "category = 'state' AND directory_scope = 'directory'",
            name="skill_preparation_scope_ck",
        ),
        sa.CheckConstraint(
            "mode IN ('initial', 'forward', 'older', 'resume')", name="skill_preparation_mode_ck"
        ),
        sa.CheckConstraint(
            "status IN ('ready', 'conflicted', 'superseded')", name="skill_preparation_status_ck"
        ),
        sa.CheckConstraint(
            "(source_state_id IS NULL AND source_checkpoint_id IS NULL AND "
            "source_epoch IS NULL) OR (source_state_id IS NOT NULL AND "
            "source_checkpoint_id IS NOT NULL AND source_epoch IS NOT NULL AND "
            "source_epoch >= 1)",
            name="skill_preparation_source_ck",
        ),
        sa.CheckConstraint(
            "target_epoch >= 1 AND directory_epoch >= 1 AND library_generation >= 0",
            name="skill_preparation_epoch_ck",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "account_id", "directory_scope", "directory_checkpoint_id"],
            [
                "skill_checkpoints.user_id",
                "skill_checkpoints.account_id",
                "skill_checkpoints.scope",
                "skill_checkpoints.id",
            ],
            name="skill_preparation_input_directory_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "account_id", "directory_scope", "result_directory_id"],
            [
                "skill_checkpoints.user_id",
                "skill_checkpoints.account_id",
                "skill_checkpoints.scope",
                "skill_checkpoints.id",
            ],
            name="skill_preparation_result_directory_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "account_id", "installation_id", "installation_epoch", "source_state_id"],
            [
                "account_skill_states.user_id",
                "account_skill_states.account_id",
                "account_skill_states.installation_id",
                "account_skill_states.installation_epoch",
                "account_skill_states.id",
            ],
            name="skill_preparation_source_state_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "account_id", "installation_id", "installation_epoch", "target_state_id"],
            [
                "account_skill_states.user_id",
                "account_skill_states.account_id",
                "account_skill_states.installation_id",
                "account_skill_states.installation_epoch",
                "account_skill_states.id",
            ],
            name="skill_preparation_target_state_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "account_id", "source_state_id", "source_checkpoint_id"],
            [
                "skill_checkpoints.user_id",
                "skill_checkpoints.account_id",
                "skill_checkpoints.state_id",
                "skill_checkpoints.id",
            ],
            name="skill_preparation_source_checkpoint_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "account_id", "target_state_id", "result_checkpoint_id"],
            [
                "skill_checkpoints.user_id",
                "skill_checkpoints.account_id",
                "skill_checkpoints.state_id",
                "skill_checkpoints.id",
            ],
            name="skill_preparation_result_checkpoint_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "category", "base_digest"],
            [
                "skill_stored_trees.user_id",
                "skill_stored_trees.category",
                "skill_stored_trees.digest",
            ],
            name="skill_preparation_base_tree_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "category", "current_digest"],
            [
                "skill_stored_trees.user_id",
                "skill_stored_trees.category",
                "skill_stored_trees.digest",
            ],
            name="skill_preparation_current_tree_fk",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "category", "incoming_digest"],
            [
                "skill_stored_trees.user_id",
                "skill_stored_trees.category",
                "skill_stored_trees.digest",
            ],
            name="skill_preparation_incoming_tree_fk",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="skill_preparation_key_uq"),
    )


def downgrade() -> None:
    """
    有使用历史或准备回执时拒绝降级丢失运行数据来源。
    """
    for table in ("skill_effective_branches", "skill_branch_preparations"):
        if op.get_bind().execute(sa.text("SELECT 1 FROM " + table + " LIMIT 1")).scalar():
            raise RuntimeError("skill branch preparation history must be retained before downgrade")
    op.drop_table("skill_branch_preparations")
    op.drop_table("skill_effective_branches")
    op.drop_constraint(
        "skill_state_installation_identity_uq", "account_skill_states", type_="unique"
    )
